<template>
  <div class="committee">
    <ul>
      <h2>United Nations Office on Drugs and Crimes</h2>
      <li>Topic: Addressing the Links Between Drug Trafficking and Terrorist Finance Networks</li>
      <li>Working Language: English</li>
      <li>Delegation Type: Dual Delegates</li>
      <li>Delegate Amount: 55 countries</li>
      <li>Dais Member:</li>
      <li>吕若慈&emsp;&emsp;&emsp;&emsp;台湾新竹科学工业园区实验中学</li>
      <li>陈亭筑&emsp;&emsp;&emsp;&emsp;台湾新竹科学工业园区实验中学</li>
      <li>施&emsp;鑫&emsp;&emsp;&emsp;&emsp;宁波诺丁汉大学</li>
      <li>侯静怡&emsp;&emsp;&emsp;&emsp;四川外国语大学</li>
      <li>刘秦婉娴&emsp;&emsp;&emsp;山东省青岛第二中学</li>
      <p>When one look upon drug trafficking and terrorism, it may be hard to draw a connection between the two. However, in reality, the two issues have quite a lot to do with one another.</p>
      <p>While terrorism requires money—money to buy weapons, support the members, and plan operations, drug trafficking has in fact provided the exact, immense amount of cash such acts need, which places drug dealing, though most addicts unaware, as one of the major backing of terrorism.</p>
      <p>Drug trafficking is a market which worth hundreds of billions USD each year. It's clear that even a small percentage would be more than sufficient for some individuals or groups to carry out terrifying attacks. So as terrorism has been one of the most pressing issues in this century, it is more than crucial for us to tackle this issue from its root, in other words, its finances.</p>
      <p>With this important piece of information, it serves as a leverage for us to combat both issues. If drug traffickers around the world are identified and tracked, it is highly possible that we will be indirectly beating terrorism as well: it is then possible that there would no longer be rapid increments of such attacks in the world.</p>
		</ul>
    <ul>
      <h2>The Third Committee of the General Assembly</h2>
      <li>Topic: Human Rights Protection in the Digital Age</li>
      <li>Working Language: English</li>
      <li>Delegation Type: Single Delegate</li>
      <li>Delegate Amount: 70 countries</li>
      <li>Dais Member:</li>
      <li>李云飞&emsp;&emsp;&emsp;&emsp;清华大学</li>
      <li>王怡然&emsp;&emsp;&emsp;&emsp;北京理工大学</li>
      <li>王奕彭&emsp;&emsp;&emsp;&emsp;南京财经大学</li>
      <li>王睿卿&emsp;&emsp;&emsp;&emsp;南京外国语学校</li>
      <li>刘靖予&emsp;&emsp;&emsp;&emsp;台湾师范大学附属高级中学</li>
      <p>Since the beginning of 21st century, the rapid development of digital technology, especially the Internet, has caused great changes worldwide, and huge conveniences are brought to people. Nonetheless, it also enhances the capacity of governments, companies and groups to undertake interception and data collection, which may violate various forms of human rights, such as individual privacy, property right, freedom of expression, even the right of life and health.</p>
      <p>By the end of 2016, the number of global web users has risen to over 3.5 billion, which means half of people all over the world are at risk of being monitored, eavesdropped or hacked without even noticing the danger. Since the disclosure of Prism Incident, the international society has become more aware of the protection of human rights in digital age. The General Assembly and UN Human Rights Council have held meetings on the topic and passed several resolutions, yet the achievement made hitherto is far from concrete. Therefore, there is still much space for future discussion.</p>
		</ul>
    <ul>
      <h2>The Committee on Data for Science and Technology</h2>
      <li>Topic: Big Data World: challenges and opportunities for sustainable development</li>
      <li>Working Language: English</li>
      <li>Delegation Type: Single Delegate</li>
      <li>Delegate Amount: 45 countries</li>
      <li>Dais Member:</li>
      <li>王以琳&emsp;&emsp;&emsp;&emsp;合肥市第一中学</li>
      <li>陈若言&emsp;&emsp;&emsp;&emsp;Brighton College</li>
      <li>李佳欣&emsp;&emsp;&emsp;&emsp;南京外国语学校</li>
      <li>赵致宇&emsp;&emsp;&emsp;&emsp;台湾新竹科学工业园区实验中学</li>
      <p>New technologies are leading to an exponential increase in the volume and types of data available, creating unprecedented possibilities for informing and transforming society and protecting the environment. Governments, companies, researchers and citizen groups are all experimenting with the new world of data, a world in which data are bigger, faster and more detailed than ever before.</p>
      <p>Data has also always been a fundamental and necessary role in the sustainable development space. The breadth of the 2030 Agenda for Sustainable Development and on-going development of Information & Communication Technology provide opportunities for a more systematic and ambitious approach to data collection, management and integration. But the unprecedented volume of data generated by the digital revolution of recent decades has led to the emergence of characterizing and understanding the complex systems that are at the heart of achieving the Sustainable Development Goals. Therefore the purpose of our conference is to explore the possibilities of data as a tool to reach the Development Goals more rapidly in our world.</p>
		</ul>
    <ul>
      <h2>United Nations Environment Program</h2>
      <li>Topic: The marine environment protection and resources exploitation</li>
      <li>Working Language: English</li>
      <li>Delegation Type: Single Delegate</li>
      <li>Delegate Amount: 60 countries</li>
      <li>Dais Member:</li>
      <li>高静怡&emsp;&emsp;&emsp;&emsp;浙江传媒学院</li>
      <li>臧英钰&emsp;&emsp;&emsp;&emsp;复旦大学</li>
      <li>贺凯箴&emsp;&emsp;&emsp;&emsp;台北市私立复兴实验高级中学</li>
      <li>李智瑶&emsp;&emsp;&emsp;&emsp;北京市一零一中学</li>
      <p>As the origin of life, ocean has covered 71% of the terrestrial area. Lapsing history of all time has been witnessing the pivotal function possessed by the marine regions, shouldering the functions of inter-continental trade and marine resources exploitation, over the millenniums.  However, due to the rapid metabolism of international community, the increasingly strong demand for natural resources has turned the focus of human beings from land to ocean-based resources. Due to decades-long over-exploitation and utilization, a new trend of maritime degradation has been put on the table of the global stage. As for the “blue route” connecting states and the fertile resource base for the sphere, the ocean cannot bear the tremendous pressure imposed by the unceasing greed.</p>
      <p>UNEP, as one of the main branches of the United Nations, is committed to tackle all kinds of environmental-related problems, and is concurrently exerting its effort on handling the intricate relationship between countries and regions. Under the main subject of marine environment protection and resources exploitation, the committee is looking forward to reaching concrete consensus, together with strong consolidation between different interested parties, to depict and to achieve a illuminated blueprint of the maritime environment.</p>
		</ul>
    <ul>
      <h2>联合国非洲经济委员会</h2>
      <li>议题：非洲地区的减贫问题</li>
      <li>工作语言：中文</li>
      <li>代表团形式：单代表</li>
      <li>代表数：80席</li>
      <li>主席团成员： </li>
      <li>余昕悦&emsp;&emsp;&emsp;&emsp;外交学院</li>
      <li>徐众钦&emsp;&emsp;&emsp;&emsp;北京市一零一中学</li>
      <li>关&emsp;欣&emsp;&emsp;&emsp;&emsp;吉林大学</li>
      <li>孙皓宇&emsp;&emsp;&emsp;&emsp;合肥北城中学</li>
      <li>李紫嫣&emsp;&emsp;&emsp;&emsp;太原外国语学校</li>
      <li class="chinesetext">百万年前，一支支冒险队从这里走出，开启了后面的一切历史；</li>
      <li class="chinesetext">数千年前，一座座金字塔在这里矗立，装点了灿烂的古老文明。</li>
      <li class="chinesetext">这里是非洲，是那个阳光灼热的阿非利加，是十数亿人生长的地方。</li>
      <li class="chinesetext">她养育了人类，却面临着别样的回馈。纵有美妙的容颜，却也在风吹雨打中陷入到万劫不复的深渊。</li>
      <li class="chinesetext">航海时代，运奴船的桅杆似乎还在沙沙作响；</li>
      <li class="chinesetext">二次大战，阿拉曼的硝烟似乎尚未悄悄远去。</li>
      <li class="chinesetext">独立运动，血与火的洗礼终于带来了暂时的喘息；</li>
      <li class="chinesetext">发展建设，钱与技的博弈又给其铐上贫困的锁链。</li>
      <li class="chinesetext">尼罗的江水，饱含多少眼泪；苏丹的秃鹫，描绘无数绝望。</li>
      <li class="chinesetext">似乎，一体化之帆与共建设之锚，开始酝酿着一幅满是希望与憧憬的画卷；</li>
      <li class="chinesetext">然而，丰满的理想与骨感的现实，最终交汇成一曲包含无奈与担忧的悲歌。</li>
      <li class="chinesetext">君不见那基础薄弱，设施残缺无从建起，教育匮乏民智未开。</li>
      <li class="chinesetext">君不见那方式单一，劳力廉价难以改进，资源贱卖杯水车薪。</li>
      <li class="chinesetext">君不见那环境压力，黄金万两未曾到来，一江毒水向东流去。</li>
      <li class="chinesetext">君不见那明争暗斗，明面春风充满善意，背地寒流暗含杀机。</li>
      <li class="chinesetext">债台高筑、基建薄弱，减贫工作从何开展？</li>
      <li class="chinesetext">蓝图宏伟，挑战重重，千年计划怎样实现？</li>
      <li class="chinesetext">联合国经济及社会理事会——非洲经济委员会期待你的答案。</li>
		</ul>
    <ul>
      <h2>1795大革命欧洲停战谈判体系</h2>
      <li>会场设置：</li>
      <li>法兰西国民公会(Convention Nationale)</li>
      <li>神圣罗马帝国常设封臣议会(Immerwährender Reichstag)</li>
      <li>反法同盟(Anti-France Coalition)</li>
      <li>工作语言：中文</li>
      <li>代表团形式：单代表</li>
      <li>代表数：190席</li>
      <li>主席团成员： </li>
      <li>张恺悦&emsp;&emsp;&emsp;&emsp;南京大学</li>
      <li>陈克朋&emsp;&emsp;&emsp;&emsp;东南大学</li>
      <li>田嘉毅&emsp;&emsp;&emsp;&emsp;北京大学</li>
      <li>刘浩宇&emsp;&emsp;&emsp;&emsp;Australian National University</li>
      <li>章&emsp;博&emsp;&emsp;&emsp;&emsp;北京林业大学</li>
      <li>蒋蓝辉&emsp;&emsp;&emsp;&emsp;上海外国语大学</li>
      <li>李&emsp;桐&emsp;&emsp;&emsp;&emsp;华东政法大学</li>
      <li>施博雅&emsp;&emsp;&emsp;&emsp;中国政法大学</li>
      <li>赵见阳&emsp;&emsp;&emsp;&emsp;合肥市第一中学</li>
      <li>蔡一霖&emsp;&emsp;&emsp;&emsp;合肥市第一中学</li>
      <li class="chinesetext">两年前的今天，全巴黎的人们在马尔斯广场焦急等待自由纪元的钟声敲响，布里索站在讲台上忠告为新时代而聚集的巴黎市民：“公民们，警惕你们手中的武器吧！他们铸造了共和国，也将毁掉共和国啊！”市民们却用巴雷尔的宣言向政府回应：“公民们!武装起来！让恐怖成为共和国的秩序！”于是自由的沃野变成了安纳其的深渊，学者向往的天堂成为了天火中的索多玛，无尽的流血与创伤让公民怒火燎原。</li>
      <li class="chinesetext">如今，鲜血已被擦干，阴霾业已扫去，来自法国各区的代表齐聚杜伊勒里宫筹划拨乱反正，对政变如三餐般熟悉的阴谋高手们则在巴黎郊区的民房中策划不可告人的秘事。面对誓在用革命的热火将帝国封建制度故纸堆焚尽的数十万法军，雷根斯堡金碧辉煌的神圣罗马帝国议会中暗流汹涌，危机四伏。百万来自全欧洲的军队在向法兰西逼近，被自由沧海环绕的欧罗巴上，新与旧碰撞的奏鸣曲已经奏响。去听那远方塞纳河边公民的呼声！美泉宫中的交响乐！去听那枪声下的嘶吼，听那皮鞭下的哭泣！蔽日硝烟下，传来远方的布告：“他说，汝去寻真理吧，开显真理，汝便自由啦。”</li>
		</ul>
    <ul>
      <h2>1938中國學界會議</h2>
      <li>议题：
      <li>①南遷學校生存問題之探討</li>
      <li>②戰時教育和正常教育之探討</li>
      <li>③學術發展及其精神延續之討論</li>
      <li>工作语言：中文</li>
      <li>代表团形式：单代表</li>
      <li>代表数：50席</li>
      <li>主席团成员： </li>
      <li>陸&emsp;倦&emsp;&emsp;&emsp;&emsp;中國人民大學</li>
      <li>于金朝&emsp;&emsp;&emsp;&emsp;中國人民大學</li>
      <li>紀懿銘&emsp;&emsp;&emsp;&emsp;中國政法大學</li>
      <li>滕明翰&emsp;&emsp;&emsp;&emsp;四川師範大學</li>
      <li class="chinesetext">“吾弟急拆：</li>
      <li class="chinesetext">惟此獨立之精神，自由之思想，歷千萬祀，與天壤而同久，共三光而永光。</li>
      <li class="chinesetext">洎七七事變爆發，國家威權逐漸下移，推及文化力量，平津三校實為中堅。今逢民族危亡之秋，救護我中華之學脈，則愈迫在眉睫矣。雖聚三校南移建長沙臨大，奈何日機突襲長沙頻仍，戰爭形勢日促。為使血脈不絕，兄等彷徨間邀於政學兩界，望賢達速來星州，共商學術之出路。</li>
      <li class="chinesetext">兄竊不遜，抄觀堂先生之章句，願與弟共勉之，亦共捍之。</li>
      <li class="chinesetext">盼復。”</li>
      <li class="chinesetext">……</li>
      <li class="chinesetext">半壁江山已然淪亡，日偽開始文化毀滅，學術前途渺茫未知……沒有權力、沒有軍隊、沒有金錢，自己只是在炮火中苟且偷生的螻蟻，究竟能做些什麼呢？</li>
      <li class="chinesetext">學術！自由！擔當！脊樑！</li>
      <li class="chinesetext">1938年春，他們聚到了一起。</li>
      <li class="chinesetext">他們需要一個答案。</li>
		</ul>
    <ul>
      <h2>儿童·育儿会议，少子化社会对策会议合同会议</h2>
      <li>议题：（日本）少子化对策的再探讨</li>
      <li>工作语言：中文</li>
      <li>代表团形式：单代表</li>
      <li>代表数：60席</li>
      <li>主席团成员： </li>
      <li>张华宇&emsp;&emsp;&emsp;&emsp;横滨国立大学</li>
      <li>李哲宇&emsp;&emsp;&emsp;&emsp;清华大学</li>
      <li>徐思慧&emsp;&emsp;&emsp;&emsp;广东金融学院</li>
      <li>刘香宁&emsp;&emsp;&emsp;&emsp;辽宁大学</li>
      <li class="chinesetext">“为了可以选择的未来”</li>
      <li class="chinesetext">少子化问题是当今世界上许多国家共同面临的问题，其中最严重的当属日本。少子化问题带来了劳动力减少、社会保障制度崩溃、世代间不平衡等诸多问题，对整个社会的未来命运产生了重大且难以预测的影响。面对少子化问题，日本社会正在积极地思考、制定和实施对策。</li>
      <li class="chinesetext">组成本会场的两个会议均由日本内阁府设置。儿童·育儿会议是为了执行“儿童·育儿支援新制度”而设置的，由社会人士组成的政策会议，而少子化社会对策会议是根据《少子化社会对策基本法》设置的综合政策推进会议，由内阁全体阁僚组成。</li>
      <li class="chinesetext">在这个会场中，“官”和“民”将进行直接的对话，在少子化问题对策实施前线的社会团体人士、地方官员、专家学者等和在日本政界顶点的内阁之间将形成管道，在对抗和合作中探讨过去的政策实绩和未来的进一步对策。社会全体和每名社会成员个人，能否从不安的现状当中脱出，获得可以选择的未来？期待各位代表经过深思熟虑后的提案。</li>
		</ul>
    <ul>
      <h2>亚洲基础设施投资开发银行</h2>
      <li>议题：国际经济合作下的基础设施建设</li>
      <li>工作语言：中文</li>
      <li>代表团形式：单代表</li>
      <li>代表数：90席</li>
      <li>主席团成员： </li>
      <li>朱泽圻&emsp;&emsp;&emsp;&emsp;哈尔滨工业大学</li>
      <li>唐&emsp;辰&emsp;&emsp;&emsp;&emsp;台湾大学</li>
      <li>唐诗雯&emsp;&emsp;&emsp;&emsp;上海立信会计金融学院</li>
      <li>龚逸雪&emsp;&emsp;&emsp;&emsp;合肥市第一中学</li>
      <li>张雨潇&emsp;&emsp;&emsp;&emsp;吉林毓文中学</li>
      <li class="chinesetext">各位代表，欢迎来到亚洲基础设施投资银行理事会。在本会场中，你们或将扮演各国在亚洲基础设施投资银行的理事，或将扮演各大国际公司的全权代表。作为一国的理事，你可以草拟项目计划书，并通过游说各国取得银行的贷款，也可以综合国家利益、区域经济发展等因素，支持合适的项目。作为国际公司的全权代表，你可以参与到各建设方案的形成过程中，并通过为项目争取贷款，最大化公司的利益。本会场的成果将不是大而概之的决议、宣言，而是一份份将要在各国落地实施、推动经济发展的项目策划书，以及属于各国、也属于全世界的经济发展的未来。</li>
		</ul>
    <ul>
      <h2>汇文省经济贸易高峰会</h2>
      <li>工作语言：中文</li>
      <li>代表团形式：单代表</li>
      <li>代表数：150</li>
      <li>主席团成员:</li>
      <li>龙昱辰&emsp;&emsp;&emsp;&emsp;南京艺术学院</li> 
      <li>徐大钧&emsp;&emsp;&emsp;&emsp;南方科技大学</li>
      <li>朱&emsp;睿&emsp;&emsp;&emsp;&emsp;深圳大学</li>
      <li>丰晨昱&emsp;&emsp;&emsp;&emsp;石家庄市第一中学</li>
      <li>乔楚涵&emsp;&emsp;&emsp;&emsp;西安交通大学附属中学</li>
      <li>秦翊城&emsp;&emsp;&emsp;&emsp;北京市第一六一中学</li>
      <li>吴宜蒙&emsp;&emsp;&emsp;&emsp;北京市一零一中学</li>
      <p class="chinesetext">非常感谢诸位能够在百忙之中保持对汇文模联的关注。风云变幻，时过境迁，改革开放在不知不觉中已历经三十余载，回首往昔，我们见证了中国从一贫如洗到富甲天下的崛起，也感受了商人从白手起家到衣锦还乡的不易；我们不再惊讶于首富交椅的数度更迭，我们逐渐习惯于茫茫商海中的尔虞我诈。在这个经济大发展大繁荣的黄金时代，人民群众对经贸相关的知识空前渴求，商业教育的低龄化趋势日益明显，市场经济走向成熟走向完善的步伐愈发坚定。</p>
      <p class="chinesetext">汇文模联经过七年的发展与磨炼，仍不忘初心，兢兢业业，始终致力于学术创新，努力创办更多贴近时代、特点鲜明的会场；汇文模联一直注重寓知于行，让广大中学生在实践中提升素养，感悟真知。在此，我们向各位代表简要介绍我们的会场——汇文省经济贸易高峰会。</p>
      <p class="chinesetext">汇文省经济贸易高峰会正竭力打造一个真实完整的商业发展环境，让代表们在体验中收获真知。参会者将分组并分别担任企业中的重要职务，从而切身体验一家企业从注册注资、争夺市场、对外投资直至转型升级的全部过程，全新的数字化经营模拟系统更将淋漓尽致的展现市场竞争的残酷。在为期五天的旅程中，参会者的意志力、应变能力、合作能力、沟通能力等都将逐一接受考验，以便于应对市场的变化无常——无论是经济政策的出台，抑或是市场信心的转变，都将一步步影响企业的决策和未来走向。但是在紧张和疲惫之余，大家同样能够体会到相聚有缘的奇妙、同舟共济的温暖、绝处逢生的刺激以及俯瞰众生的快感。在2018汇文模联中，我们将尽心竭力，为代表们奉上更为精彩的学术盛宴。</p>
      <p class="chinesetext">汇文省经济贸易高峰会衷心期待各位代表的加入！</p>
    </ul>
    <ul>
      <h2>中国系统</h2>
      <li>议题：高速公路改革</li>
      <li>工作语言：中文</li>
      <li>代表团形式：单代表</li> 
      <li>代表数：210</li>
      <li>主席团成员： </li>
      <h3>办公厅</h3>
      <li>费&emsp;凡&emsp;&emsp;&emsp;华东政法大学</li>
      <li>张祖瑞&emsp;&emsp;&emsp;中国政法大学</li>
      <li>李宸廷&emsp;&emsp;&emsp;昆明市第一中学</li>
      <li>章思怡&emsp;&emsp;&emsp;合肥一六八中学</li>
      <h3>省人大</h3>
      <li>主席团成员： </li>
      <li>贾语涵&emsp;&emsp;&emsp;澳门科技大学</li>
      <li>宋启昕&emsp;&emsp;&emsp;天津市第一中学</li>
      <li>王咏婵&emsp;&emsp;&emsp;北京市一零一中学</li>
      <li>鲍嘉文&emsp;&emsp;&emsp;西安交通大学附属中学</li>
      <h3>国务院</h3>
      <li>主席团成员： </li>
      <li>周明妍&emsp;&emsp;&emsp;北京市一零一中学</li>
      <li>李兆升&emsp;&emsp;&emsp;合肥一六八中学</li>
      <li>尹逸山&emsp;&emsp;&emsp;昆明市第一中学</li>
      <li>王宜扬&emsp;&emsp;&emsp;西安铁一中学</li>
      <h3>省政府</h3>
      <li>主席团成员： </li>
      <li>刘&emsp;睿&emsp;&emsp;&emsp;天津大学</li>
      <li>田佑雯&emsp;&emsp;&emsp;北京市一零一中学</li>
      <li>石雨涵&emsp;&emsp;&emsp;武汉外国语学校</li>
      <li>张惠翔&emsp;&emsp;&emsp;大庆市第一中学</li>
      <p class="chinesetext">它，连接着传统与现代；它，勾勒着过去与未来。在它身上，你可想到，那重卡中的物产丰隆；你可听到，那轿车中的欢声笑语；你可感到，那客运中的奔波不停；你可看到，那灯光中的川流不息。它总是这样默默无闻，却又总是这样功勋卓著。它像一根根筋骨，为联通与交流创造条件；它像一排排血管，为发展和繁荣输送动力。它，连接着传统与现代；它，勾勒着过去与未来。在它身上，你可想到，那重卡中的物产丰隆；你可听到，那轿车中的欢声笑语；你可感到，那客运中的奔波不停；你可看到，那灯光中的川流不息。它总是这样默默无闻，却又总是这样功勋卓著。它像一根根筋骨，为联通与交流创造条件；它像一排排血管，为发展和繁荣输送动力。</p>
      <p class="chinesetext">它就是高速公路。今天，中国的高速公路总里程已位居全球第一，其对经济社会发展的重要作用也在不断体现。和水路建设共享的1.8万亿元年度计划，也为高速公路系统的进一步发展奠定了坚实的基础。然而，建设与财政之间的矛盾、成本与收费之间的权衡、事权与财权之间的分裂，不仅成为了发展的束缚，也成为了百姓的困扰。中央与地方，政府与社会，都充分领会到一场试点的重要性。然，冰冻三尺，非一日之寒，推陈出新，更需共同努力。正值汇文省人民代表大会召开，这个经济发达的省份，又能否成为这一改革的排头兵，答案握在你们的手中。</p>
      <p class="chinesetext">各位代表！</p>
      <p class="chinesetext">使命重在担当，实干铸就辉煌。当前我国发展面临内外诸多矛盾叠加、风险隐患交汇的严峻挑战，高速公路的改革也越来越成为社会关注的话题。在此，中国系统需要你迎难而上，以充足的准备迎接会议的挑战；需要你们砥砺前行，以不懈的努力参与改革的进程；更需要你们同心同德，以务实的态度贯彻互惠的精神；更需要你们开拓进取，以创新的思维迸发灵感的火花。在全面建成小康社会的开局阶段，让我们与全党、全军、各族人民紧密团结在一起，以一份在高速公路改革问题上的优秀答卷助力经济社会的健康发展，努力创造无愧于时代和人民的新业绩。</p>
      <p class="chinesetext">中国系统，等你加入。</p>
		</ul>
  </div>
</template>

<script>
export default {
  name: 'committee2017ss',
  data () {
    return {
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
  .committee {
    display: block;
    width: 1200px;    
    margin-top: 20px;
  }

  .committee ul{
    list-style: none;
  }

  p {
    text-align: justify;
  }
</style>
